apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-argocd-application-controller
  namespace: phpinfo-helm-sebastian
rules:
  - apiGroups:
      - ''
    verbs:
      - create
    resources:
      - services
  - apiGroups:
      - apps
    verbs:
      - create
      - patch
    resources:
      - deployments
